apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-microservice
spec:
  selector:
    matchLabels:
      app: user-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: user-microservice
    spec:
      containers:
      - name: user-microservice0
        image: manjorno.azurecr.io/user-microservice
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: "http://52.234.161.164/auth"
        - name: KEYCLOAK_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: username
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: password
        - name : KEYCLOAK_CLIENTCLI_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: secret
        ports:
        - containerPort: 3100

---

apiVersion: v1
kind: Service
metadata:
    name: user-microservice
spec:
    ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
        app: user-microservice
    type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: user-microservice
spec:
    rules:
    - http:
        paths:
        - path: /api/users
          backend:
            serviceName: user-microservice
            servicePort: 3100