apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-microservice
spec:
  selector:
    matchLabels:
      app: users-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: users-microservice
    spec:
      containers:
      - name: users-microservice
        image: manjorno.azurecr.io/users-microservice
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: keycloak.keycloak.svc.cluster.local
        - name: KEYCLOAK_USERNAME
          value: backendapp
        - name: KEYCLOAK_PASSWORD
          value: i5JtyQIWfldiwZFuK64w5emej5zGjpde
        - name : KEYCLOAK_CLIENTCLI_SECRET
          value: MVZQhNqty4FIMKcWFgOjsLc4zoE8G4hC
        ports:
        - containerPort: 3100

---

apiVersion: v1
kind: Service
metadata:
  name: users-microservice
spec:
  selector:
    app: users-microservice
  ports:
  - port: 3100
    targetPort: 3100