apiVersion: apps/v1
kind: Deployment
metadata:
  name: manjorno-users
spec:
  selector:
    matchLabels:
      app: manjorno-users
  replicas: 1
  template:
    metadata:
      labels:
        app: manjorno-users
    spec:
      containers:
      - name: manjorno-users
        image: manjorno1.azurecr.io/manjorno-users
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: http://20.90.169.171:8080/auth
        - name: KEYCLOAK_USERNAME
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: username
              optional: false
        - name: KEYCLOAK_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: password
              optional: false
        - name : KEYCLOAK_CLIENTCLI_SECRET
          valueFrom:
            secretKeyRef:
              name: keycloak-secret
              key: client_cli_secret
              optional: false
        ports:
        - containerPort: 3100

---

apiVersion: v1
kind: Service
metadata:
  name: manjorno-users
spec:
  selector:
    app: manjorno-users
  ports:
  - port: 3100
    targetPort: 3100