apiVersion: apps/v1
kind: Deployment
metadata:
  name: manjorno-users
spec:
  selector:
    matchLabels:
      app: manjorno-users
  replicas: 1
  template:
    metadata:
      labels:
        app: manjorno-users
    spec:
      containers:
      - name: manjorno-users
        image: manjorno.azurecr.io/manjorno-users
        imagePullPolicy: Always
        env:
        - name: KEYCLOAK_URL
          value: keycloak.keycloak.svc.cluster.local
        - name: KEYCLOAK_USERNAME
          value: backendapp
        - name: KEYCLOAK_PASSWORD
          value: i5JtyQIWfldiwZFuK64w5emej5zGjpde
        - name : KEYCLOAK_CLIENTCLI_SECRET
          value: MVZQhNqty4FIMKcWFgOjsLc4zoE8G4hC
        ports:
        - containerPort: 3100

---

apiVersion: v1
kind: Service
metadata:
  name: manjorno-users
spec:
  selector:
    app: manjorno-users
  ports:
  - port: 3100
    targetPort: 3100